### ISSUE TITLE
Does not function when popup is disabled

### ISSUE THREAD

**Issue by rodalpho** [siku2/script.service.sponsorblock#4]
When I disable the sponsorblock "We just skipped this sponsor" popup the script does nothing at all. It no longer skips. Expected behavior is for it to continue skipping sponsored sections silently, with no feedback to the user.

**Comment by siku2** [comment]
Thanks for the report, I will take a look as soon as possible.

**Comment by siku2** [comment]
@rodalpho, I tried to reproduce this and in my case it worked exactly like you described it should; that is, it skipped the sponsor silently.

In order to find out what went wrong in your case I would need to see the logs.
It would also help to know under which circumstances this happened.
My go-to video for testing is [this one](https://www.youtube.com/watch?v=SQCfOjhguO0) and it skipped the first sponsor segment without any problems.

**Comment by rodalpho** [comment]
I just tested on a bunch of videos and was unable to reproduce. Maybe I had skipped past the start point, and that broke it. Sorry for wasting your time on this and thanks for the script!

**Comment by siku2** [comment]
Oh don't worry about it. Thank you for taking the time to file an issue in the first place!

The script currently has issues with sponsor segments right at the start of the video. Maybe that's what happened to you.

This is because the script has to wait for the video to load in order to determine the video id and then of course it has to communicate with the SponsorBlock API. Because of this delay it is often the case that the script can only start skipping segments a few seconds into the video.

The YouTube plugin added a notification system specifically to combat this issue and I'm currently working on implementing this.
